---
- name: playbook to uninstall httpd
  hosts: all
  become: true
  tasks:
   - name : stop httpd
     service:
      name: httpd
      state: stopped
   - name : uninstall httpd
     yum:
      name : httpd
      state: absent


