---
# tasks file for setup-apache-roles
- name: install httpd on RedHat
  yum:
   name: httpd
   state: present
  when: ansible_os_family== "RedHat"
  notify: start httpd

- name : install apache on Debian
  apt:
   name: apache2
   state: present
  when: ansible_os_family == "Debian" 
  notify : start apache2

- name: copy index file
  copy:
   src: /home/ansadmin/index.html
   dest: /var/www/html
   mode: 0666 
